# Generated by Django 5.1.6 on 2025-02-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=70)),
                ("model", models.CharField(max_length=70)),
                ("color", models.CharField(max_length=70)),
                ("price", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_sold", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(upload_to="images/")),
                ("is_existence", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phone",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=70)),
                ("model", models.CharField(max_length=70)),
                ("color", models.CharField(max_length=70)),
                ("price", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField(blank=True, null=True)),
                ("is_sold", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_existence", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "ordering": ["-created_date"],
            },
        ),
    ]
