# Generated by Django 5.1.4 on 2025-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_comment_delete_product_alter_phone_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="phone",
            field=models.CharField(max_length=9),
        ),
    ]
